### PR TITLE
Always allow buy arrows

### PR DESCRIPTION
**Pull request by icogn**
- Patch MsgFlow function to always say you are not at max arrows. This allows you to buy arrows even if you are at max (fixes Iza Steal Bomb Bag - Castle Town Goron issue).
- Most `mod.h` lines in the diff are from the file having a mixture of LF and CRLF line endings.

### CODE REVIEW

**Review by Zephiles — CHANGES_REQUESTED** [review]
This code forces `query024` to always return `true`, which will mess with anything else that happens to use this function. Therefore, additional code is needed for making sure it only returns `true` under specific circumstances.

**Comment by icogn** [comment]
To clarify the reason I haven't done anything else on this PR:
- The `query024` function essentially checks if your arrows are at max or not.
- The only place I am aware that this check happens is when you are buying arrows. (The function is part of `MsgFlow`)
- The desired outcome was that you would always be able to buy arrows even if you are considered to be at max (either you simply are at max, or you are considered to be at max after doing Iza related things when you don't have the bow), and the code handles those cases as is.

I am not aware of any other locations where this "arrows not at max?" check would be used. I would be fine to make changes if we can find a reproducible issue with simply returning true or to investigate a particular situation where we think it might cause an issue. But as it stands, I don't believe such a case exists, and I do not intend to spend time overcomplicating the code unless there is evidence that it needs to be updated.

- Given that the function is part of MsgFlow, I think it is only used for picking between a Yes or No scenario at a fork in a conversation (something with text boxes at the bottom of the screen). The only one I am aware of is when buying arrows. There is a fork with 2 outcomes: you are able to buy the arrows and the conversation flows in that direction or you are not able to buy arrows and the conversation flows in that direction. Which path you take is a result of the query024 function, but we determined that we always want to take the path where you are able to buy the arrows, hence the simple implementation. I don't believe there are any conversations which would take an undesirable fork as a result of thinking you are not at max arrows. I currently have no reason to believe any differently, and I have no intention of spending my free time chasing ghosts or writing code I don't believe in. If someone else knows what changes they would like to be made, they are welcome to make those changes.

**Comment by icogn** [comment]
You will be pleased to know that I found another place which uses this function while looking into something else.

After starting the Iza minigame where she gives you the bomb bag, you can talk to her with a few different outcomes:

Each options starts with "Hey, hurry up and take out that rock with your bomb arrows! You know how to make bomb arrows, right? Just set your bow on the Items screen, then choose bombs and press R to combine them."
- If you have more than 0 ammo for the Lent Bomb Bag and for the Bow, she follows with "We've got tons of bombs and arrows, so just holler if you need them!".
- If you have 0 ammo for the Lent Bomb Bag and more than 0 for the Bow, she follows with "What? You used all your bombs? Well, here you go!" and she maxes out the ammo for the Lent Bomb Bag.
- If you have more than 0 ammo for the Lent Bomb Bag and 0 for the Bow, she follows with "What? You used all your arrows? Well, here you go!" and maxes out the ammo for the Bow.
- If you have 0 ammo for both the Lent Bomb Bag and the Bow, she follows with "What? You used all your bombs and arrows? Well, here you go!" and maxes out the ammo for the Lent Bomb Bag and the Bow.

So the side effect of the PR code as written would be that your arrows will always be maxed out after talking to her in this context even if you had more than 0, which is not exactly a problem but anyway.

A more detailed description of what the function does:
Takes your current arrow count, subtracts a provided number from the count, and returns true if the result is negative. Put differently, it returns true if your current arrow count is less than a provided number, meaning this function is probably used for any Msg Flows which branch based on your arrow count.

It occurred to me that I actually do have a way to determine which RELs call this function, so I may be able to provide a list of these in the following weeks. Then a decision can be made about what kind of conditionals, if any, should be added to the code in the PR.

**Comment by lunarsoap5** [comment]
Manually corrected conflicts. Going to go ahead and merge this ahead of 0.20b release, where the code in this PR was modified.

**Pull request merged**
